# Generated by Django 3.2.5 on 2021-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_description',
            field=models.CharField(default='Add a reminder', max_length=40),
        ),
    ]
