# Generated by Django 3.2.5 on 2021-11-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reminder_reminder_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['remind_date']},
        ),
    ]
