# Generated by Django 3.2.5 on 2021-11-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reminder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
